<?php

use Lib\MainLayout;
use Lib\Request;

MainLayout::$title = !empty(MainLayout::$title) ? MainLayout::$title : 'LabWeb';
MainLayout::$description = !empty(MainLayout::$description) ? MainLayout::$description : 'Generated by create Prisma PHP App';

?>

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <?= MainLayout::outputMetadata(); ?>
    <link rel="icon" href="<?= Request::baseUrl; ?>/favicon.ico" type="image/x-icon" sizes="16x16">

    <link href="<?= Request::baseUrl; ?>/css/index.css" rel="stylesheet">
    <script src="<?= Request::baseUrl; ?>/js/json5.min.js"></script>
    <script src="<?= Request::baseUrl; ?>/js/index.js"></script>
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- Dynamic Head -->
    <?= MainLayout::outputHeadScripts() ?>
</head>

<body>
    <?= MainLayout::$children; ?>
    <!-- Dynamic Footer -->
    <?= MainLayout::outputFooterScripts(); ?>
</body>

</html>